import type { LawFirm } from '../../types';

export const mockFirms: LawFirm[] = [
  {
    id: 'firm-001',
    firm_name: 'Al Mansoori Advocates and Legal Consultants',
    firm_name_ar: 'المنصوري للمحامين والمستشارين القانونيين',
    contact_email: 'info@almansoori.ae',
    phone: '+971-4-555-0101',
    trade_licence_number: 'CN-2019-12345',
    licence_jurisdiction: 'onshore',
    office_address: 'Business Bay, Opus Tower, Floor 15',
    emirate: 'Dubai',
    years_experience: 18,
    specializations: ['corporate', 'business-setup', 'contracts', 'banking'],
    languages: ['en', 'ar'],
    logo_url: '',
    response_sla_hours: 0.5,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'elite',
    rating_avg: 4.9,
    rating_count: 234
  },
  {
    id: 'firm-002',
    firm_name: 'Habtoor & Partners',
    firm_name_ar: 'حبtoor وشركاؤه',
    contact_email: 'legal@habtoorpartners.ae',
    phone: '+971-4-555-0202',
    trade_licence_number: 'CN-2018-23456',
    licence_jurisdiction: 'onshore',
    office_address: 'Sheikh Zayed Road, Emirates Towers, Floor 32',
    emirate: 'Dubai',
    years_experience: 12,
    specializations: ['property', 'construction', 'disputes', 'insurance'],
    languages: ['en', 'ar'],
    logo_url: '',
    response_sla_hours: 1,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'pro',
    rating_avg: 4.7,
    rating_count: 178
  },
  {
    id: 'firm-003',
    firm_name: 'Rashid Al Owais Law Firm',
    firm_name_ar: 'مكتب راشد العويس للمحاماة',
    contact_email: 'info@alowaislaw.ae',
    phone: '+971-2-555-0303',
    trade_licence_number: 'CN-2020-34567',
    licence_jurisdiction: 'onshore',
    office_address: 'Corniche Road, Al Maqam Tower, Floor 8',
    emirate: 'Abu Dhabi',
    years_experience: 8,
    specializations: ['family', 'wills', 'inheritance', 'criminal'],
    languages: ['en', 'ar'],
    logo_url: '',
    response_sla_hours: 2,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'pro',
    rating_avg: 4.6,
    rating_count: 89
  },
  {
    id: 'firm-004',
    firm_name: 'Emirates Shield Legal',
    firm_name_ar: 'درع الإمارات القانوني',
    contact_email: 'contact@emirateshield.ae',
    phone: '+971-4-555-0404',
    trade_licence_number: 'CN-2021-45678',
    licence_jurisdiction: 'DIFC',
    office_address: 'Gate Village, Building 3, Level 1',
    emirate: 'DIFC',
    years_experience: 5,
    specializations: ['corporate', 'banking', 'ip', 'contracts'],
    languages: ['en', 'ar', 'ru'],
    logo_url: '',
    response_sla_hours: 0.25,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'elite',
    rating_avg: 4.8,
    rating_count: 156
  },
  {
    id: 'firm-005',
    firm_name: 'Gulf Horizon Advocates',
    firm_name_ar: 'محامو آفاق الخليج',
    contact_email: 'info@gulfhorizon.ae',
    phone: '+971-4-555-0505',
    trade_licence_number: 'CN-2017-56789',
    licence_jurisdiction: 'onshore',
    office_address: 'JLT, Cluster ICD, Floor 22',
    emirate: 'Dubai',
    years_experience: 10,
    specializations: ['employment-hr', 'disputes', 'employment-issues'],
    languages: ['en', 'ar', 'hi'],
    logo_url: '',
    response_sla_hours: 4,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'pro',
    rating_avg: 4.5,
    rating_count: 112
  },
  {
    id: 'firm-006',
    firm_name: 'Desert Rose Legal Consultants',
    firm_name_ar: 'استشارات وردة الصحراء القانونية',
    contact_email: 'legal@desertrose.ae',
    phone: '+971-6-555-0606',
    trade_licence_number: 'CN-2022-67890',
    licence_jurisdiction: 'onshore',
    office_address: 'Al Majaz, Sahara Centre Road, Tower B',
    emirate: 'Sharjah',
    years_experience: 3,
    specializations: ['family', 'wills', 'harassment', 'translation'],
    languages: ['en', 'ar'],
    logo_url: '',
    response_sla_hours: 8,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'free',
    rating_avg: 4.2,
    rating_count: 34
  },
  {
    id: 'firm-007',
    firm_name: 'Falcon Legal Group',
    firm_name_ar: 'مجموعة الصقر القانونية',
    contact_email: 'info@falconlegal.ae',
    phone: '+971-2-555-0707',
    trade_licence_number: 'CN-2016-78901',
    licence_jurisdiction: 'onshore',
    office_address: 'Al Reem Island, Sun & Sky Towers, Floor 18',
    emirate: 'Abu Dhabi',
    years_experience: 11,
    specializations: ['criminal', 'white-collar', 'disputes'],
    languages: ['en', 'ar'],
    logo_url: '',
    response_sla_hours: 0.5,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'elite',
    rating_avg: 4.9,
    rating_count: 201
  },
  {
    id: 'firm-008',
    firm_name: 'Oasis Law Firm',
    firm_name_ar: 'مكتب الواحة للمحاماة',
    contact_email: 'contact@oasislaw.ae',
    phone: '+971-4-555-0808',
    trade_licence_number: 'CN-2020-89012',
    licence_jurisdiction: 'onshore',
    office_address: 'Deira, Gold Souk Area, Building 45',
    emirate: 'Dubai',
    years_experience: 6,
    specializations: ['property', 'rental', 'attestation', 'notary'],
    languages: ['en', 'ar', 'hi', 'ur'],
    logo_url: '',
    response_sla_hours: 2,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'pro',
    rating_avg: 4.4,
    rating_count: 87
  },
  {
    id: 'firm-009',
    firm_name: 'Pearl Coast Advocates',
    firm_name_ar: 'محامو ساحل اللؤلؤ',
    contact_email: 'legal@pearlcoast.ae',
    phone: '+971-7-555-0909',
    trade_licence_number: 'CN-2019-90123',
    licence_jurisdiction: 'onshore',
    office_address: 'Al Hamra Village, Office 12',
    emirate: 'Ras Al Khaimah',
    years_experience: 7,
    specializations: ['construction', 'property', 'contracts'],
    languages: ['en', 'ar'],
    logo_url: '',
    response_sla_hours: 6,
    status: 'approved',
    accepting_new_cases: false,
    tier: 'free',
    rating_avg: 4.1,
    rating_count: 45
  },
  {
    id: 'firm-010',
    firm_name: 'Skyline Legal Partners',
    firm_name_ar: 'شركاء سكاين القانونيون',
    contact_email: 'info@skylinelaw.ae',
    phone: '+971-4-555-1010',
    trade_licence_number: 'CN-2021-01234',
    licence_jurisdiction: 'ADGM',
    office_address: 'Al Maryah Island, Al Maryah Central, Level 15',
    emirate: 'ADGM',
    years_experience: 4,
    specializations: ['corporate', 'banking', 'ip', 'white-collar'],
    languages: ['en', 'zh'],
    logo_url: '',
    response_sla_hours: 1,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'elite',
    rating_avg: 4.7,
    rating_count: 123
  },
  {
    id: 'firm-011',
    firm_name: 'Al Shamsi Legal Consultancy',
    firm_name_ar: 'استشارات الشامسي القانونية',
    contact_email: 'info@alshamsilegal.ae',
    phone: '+971-6-555-1111',
    trade_licence_number: 'CN-2018-12346',
    licence_jurisdiction: 'onshore',
    office_address: 'University City Road, Building 7',
    emirate: 'Sharjah',
    years_experience: 9,
    specializations: ['injury', 'insurance', 'employment-issues'],
    languages: ['en', 'ar'],
    logo_url: '',
    response_sla_hours: 3,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'pro',
    rating_avg: 4.3,
    rating_count: 67
  },
  {
    id: 'firm-012',
    firm_name: 'Palm Tree Legal Services',
    firm_name_ar: 'خدمات شجرة النخيل القانونية',
    contact_email: 'legal@palmtree.ae',
    phone: '+971-4-555-1212',
    trade_licence_number: 'CN-2022-23457',
    licence_jurisdiction: 'onshore',
    office_address: 'JBR, Rimal Tower, Floor 10',
    emirate: 'Dubai',
    years_experience: 3,
    specializations: ['family', 'wills', 'notary', 'attestation'],
    languages: ['en', 'ar', 'fil'],
    logo_url: '',
    response_sla_hours: 4,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'free',
    rating_avg: 3.9,
    rating_count: 28
  },
  {
    id: 'firm-013',
    firm_name: 'Heritage Law Associates',
    firm_name_ar: 'جمعية التراث للقانون',
    contact_email: 'info@heritagelaw.ae',
    phone: '+971-2-555-1313',
    trade_licence_number: 'CN-2015-34578',
    licence_jurisdiction: 'onshore',
    office_address: 'Al Bateen, Villa 23',
    emirate: 'Abu Dhabi',
    years_experience: 12,
    specializations: ['business-setup', 'corporate', 'contracts'],
    languages: ['en', 'ar'],
    logo_url: '',
    response_sla_hours: 1,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'pro',
    rating_avg: 4.6,
    rating_count: 145
  },
  {
    id: 'firm-014',
    firm_name: 'Marina Legal Solutions',
    firm_name_ar: 'حلول المارينا القانونية',
    contact_email: 'contact@marinalegal.ae',
    phone: '+971-4-555-1414',
    trade_licence_number: 'CN-2020-45689',
    licence_jurisdiction: 'DIFC',
    office_address: 'Marina Walk, Tower 5, Office 1505',
    emirate: 'DIFC',
    years_experience: 5,
    specializations: ['banking', 'ip', 'corporate', 'disputes'],
    languages: ['en', 'ar', 'ru'],
    logo_url: '',
    response_sla_hours: 0.75,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'pro',
    rating_avg: 4.5,
    rating_count: 98
  },
  {
    id: 'firm-015',
    firm_name: 'Golden Sands Advocates',
    firm_name_ar: 'محامو الرمال الذهبية',
    contact_email: 'legal@goldensands.ae',
    phone: '+971-9-555-1515',
    trade_licence_number: 'CN-2021-56790',
    licence_jurisdiction: 'onshore',
    office_address: 'Al Ain Mall Road, Plaza Building',
    emirate: 'Abu Dhabi',
    years_experience: 6,
    specializations: ['construction', 'property', 'rental'],
    languages: ['en', 'ar', 'hi'],
    logo_url: '',
    response_sla_hours: 5,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'free',
    rating_avg: 3.7,
    rating_count: 41
  },
  {
    id: 'firm-016',
    firm_name: 'Crescent Moon Law Firm',
    firm_name_ar: 'مكتب هلال القمر للمحاماة',
    contact_email: 'info@crescentmoon.ae',
    phone: '+971-4-555-1616',
    trade_licence_number: 'CN-2019-67891',
    licence_jurisdiction: 'onshore',
    office_address: 'Al Barsha, Mall of the Emirates Area',
    emirate: 'Dubai',
    years_experience: 7,
    specializations: ['harassment', 'criminal', 'family'],
    languages: ['en', 'ar'],
    logo_url: '',
    response_sla_hours: 2,
    status: 'pending',
    accepting_new_cases: false,
    tier: 'pro',
    rating_avg: 0,
    rating_count: 0
  },
  {
    id: 'firm-017',
    firm_name: 'Arabian Shield Legal',
    firm_name_ar: 'الدرع العربي القانوني',
    contact_email: 'legal@arabianshield.ae',
    phone: '+971-3-555-1717',
    trade_licence_number: 'CN-2022-78902',
    licence_jurisdiction: 'onshore',
    office_address: 'Al Ain, Industrial Area, Building 9',
    emirate: 'Abu Dhabi',
    years_experience: 4,
    specializations: ['employment-hr', 'contracts', 'disputes'],
    languages: ['en', 'ar', 'hi'],
    logo_url: '',
    response_sla_hours: 3,
    status: 'pending',
    accepting_new_cases: false,
    tier: 'free',
    rating_avg: 0,
    rating_count: 0
  },
  {
    id: 'firm-018',
    firm_name: 'Oyster Bay Legal Consultants',
    firm_name_ar: 'استشارات خليج المحار القانونية',
    contact_email: 'info@oysterbay.ae',
    phone: '+971-4-555-1818',
    trade_licence_number: 'CN-2021-89013',
    licence_jurisdiction: 'onshore',
    office_address: 'Dubai Marina, Marina Plaza, Floor 28',
    emirate: 'Dubai',
    years_experience: 5,
    specializations: ['ip', 'corporate', 'contracts'],
    languages: ['en', 'ar', 'zh'],
    logo_url: '',
    response_sla_hours: 2,
    status: 'pending',
    accepting_new_cases: false,
    tier: 'pro',
    rating_avg: 0,
    rating_count: 0
  },
  {
    id: 'firm-019',
    firm_name: 'Dune Protector Advocates',
    firm_name_ar: 'محامو حامي الكثبان',
    contact_email: 'legal@duneprotector.ae',
    phone: '+971-4-555-1919',
    trade_licence_number: 'CN-2020-90124',
    licence_jurisdiction: 'onshore',
    office_address: 'Al Nahda, Sahara Centre, Tower A',
    emirate: 'Sharjah',
    years_experience: 8,
    specializations: ['property', 'rental', 'family'],
    languages: ['en', 'ar'],
    logo_url: '',
    response_sla_hours: 3,
    status: 'rejected',
    accepting_new_cases: false,
    tier: 'free',
    rating_avg: 2.1,
    rating_count: 12
  },
  {
    id: 'firm-020',
    firm_name: 'Sapphire Justice Partners',
    firm_name_ar: 'شركاء عدالة الياقوت الأزرق',
    contact_email: 'info@sapphirejustice.ae',
    phone: '+971-4-555-2020',
    trade_licence_number: 'CN-2023-01235',
    licence_jurisdiction: 'DIFC',
    office_address: 'Emirates Gateway, Building 6, Level 3',
    emirate: 'DIFC',
    years_experience: 3,
    specializations: ['banking', 'corporate', 'white-collar'],
    languages: ['en', 'ar'],
    logo_url: '',
    response_sla_hours: 1,
    status: 'approved',
    accepting_new_cases: true,
    tier: 'elite',
    rating_avg: 4.8,
    rating_count: 89
  }
];
