import type { LawyerReview } from '../../types';

export const mockReviews: LawyerReview[] = [
  {
    id: 'review-001',
    case_id: 'case-001',
    reviewer_user_id: 'user-client-001',
    firm_id: 'firm-002',
    rating: 5.0,
    category_ratings: { communication: 5, timeliness: 5, expertise: 5, value: 5 },
    title: 'Excellent property dispute resolution',
    body: 'Habtoor & Partners handled my tenant dispute with exceptional professionalism. They secured full return of my security deposit plus compensation. Highly recommended!',
    created_at: '2024-12-10T09:00:00Z',
    is_verified: true
  },
  {
    id: 'review-002',
    case_id: 'case-003',
    reviewer_user_id: 'user-client-003',
    firm_id: 'firm-003',
    rating: 4.8,
    category_ratings: { communication: 5, timeliness: 4, expertise: 5, value: 5 },
    title: 'Compassionate and effective family law support',
    body: 'Fatima handled my custody case with incredible care and legal expertise. She understood the emotional aspects while staying focused on achieving the best outcome for my children.',
    created_at: '2024-12-05T11:30:00Z',
    is_verified: true
  },
  {
    id: 'review-003',
    case_id: 'case-004',
    reviewer_user_id: 'user-client-004',
    firm_id: 'firm-005',
    rating: 4.5,
    category_ratings: { communication: 4, timeliness: 5, expertise: 5, value: 4 },
    title: 'Successfully recovered my end of service benefits',
    body: 'After unfair termination, Gulf Horizon fought for my rights and secured all my dues plus additional compensation. The process was smooth and well-communicated.',
    created_at: '2024-11-28T14:00:00Z',
    is_verified: true
  },
  {
    id: 'review-004',
    case_id: 'case-007',
    reviewer_user_id: 'user-client-002',
    firm_id: 'firm-007',
    rating: 5.0,
    category_ratings: { communication: 5, timeliness: 5, expertise: 5, value: 5 },
    title: 'Outstanding criminal defense',
    body: 'Falcon Legal Group provided exceptional defense against serious fraud allegations. Their expertise in white-collar crime was evident throughout. Charges were dismissed.',
    created_at: '2024-12-12T10:00:00Z',
    is_verified: true
  },
  {
    id: 'review-005',
    case_id: 'case-008',
    reviewer_user_id: 'user-client-003',
    firm_id: 'firm-013',
    rating: 4.6,
    category_ratings: { communication: 5, timeliness: 4, expertise: 5, value: 4 },
    title: 'Professional contract review service',
    body: 'Heritage Law Associates thoroughly reviewed and negotiated our commercial lease. They identified critical issues that saved us significant money. Very thorough approach.',
    created_at: '2024-11-20T13:00:00Z',
    is_verified: true
  },
  {
    id: 'review-006',
    case_id: 'case-009',
    reviewer_user_id: 'user-client-004',
    firm_id: 'firm-011',
    rating: 4.3,
    category_ratings: { communication: 4, timeliness: 4, expertise: 5, value: 4 },
    title: 'Effective workplace injury claim handling',
    body: 'Al Shamsi Legal handled my workplace injury case competently. They secured fair compensation for medical expenses and lost wages. Communication could be more frequent.',
    created_at: '2024-12-08T15:30:00Z',
    is_verified: true
  },
  {
    id: 'review-007',
    case_id: 'case-012',
    reviewer_user_id: 'user-client-003',
    firm_id: 'firm-008',
    rating: 4.4,
    category_ratings: { communication: 5, timeliness: 4, expertise: 4, value: 4 },
    title: 'Efficient document attestation',
    body: 'Oasis Law Firm completed the power of attorney attestation quickly and efficiently. The process was straightforward and well-explained in both Arabic and English.',
    created_at: '2024-11-15T11:00:00Z',
    is_verified: true
  },
  {
    id: 'review-008',
    case_id: 'case-014',
    reviewer_user_id: 'user-client-004',
    firm_id: 'firm-006',
    rating: 4.2,
    category_ratings: { communication: 4, timeliness: 4, expertise: 4, value: 5 },
    title: 'Accurate legal translation service',
    body: 'Desert Rose provided accurate Hindi translation of legal documents. The certified translation was accepted by the court without issues. Good value for money.',
    created_at: '2024-11-10T09:30:00Z',
    is_verified: true
  },
  {
    id: 'review-009',
    case_id: 'case-001',
    reviewer_user_id: 'user-client-001',
    firm_id: 'firm-001',
    rating: 4.9,
    category_ratings: { communication: 5, timeliness: 5, expertise: 5, value: 4 },
    title: 'Top-tier corporate advisory',
    body: 'Al Mansoori Advocates provided exceptional service. Their response time is unmatched and their expertise is evident. Premium service that delivers results.',
    created_at: '2024-12-01T10:00:00Z',
    is_verified: true
  },
  {
    id: 'review-010',
    case_id: 'case-002',
    reviewer_user_id: 'user-client-002',
    firm_id: 'firm-004',
    rating: 4.8,
    category_ratings: { communication: 5, timeliness: 5, expertise: 5, value: 4 },
    title: 'Seamless DIFC business setup',
    body: 'Emirates Shield Legal made the DIFC company setup process smooth and efficient. Their knowledge of free zone regulations is exceptional. Fast responses to all queries.',
    created_at: '2024-12-03T14:00:00Z',
    is_verified: true
  },
  {
    id: 'review-011',
    case_id: 'case-005',
    reviewer_user_id: 'user-client-005',
    firm_id: 'firm-003',
    rating: 3.8,
    category_ratings: { communication: 4, timeliness: 3, expertise: 4, value: 4 },
    title: 'Decent service but could be faster',
    body: 'Rashid Al Owais firm provided competent service for my IP case. The legal advice was sound but response times were slower than expected for the premium charged.',
    created_at: '2024-11-30T16:00:00Z',
    is_verified: true
  },
  {
    id: 'review-012',
    case_id: 'case-006',
    reviewer_user_id: 'user-client-001',
    firm_id: 'firm-004',
    rating: 4.7,
    category_ratings: { communication: 5, timeliness: 5, expertise: 5, value: 4 },
    title: 'Professional will drafting service',
    body: 'Emirates Shield drafted my DIFC will with great care and attention to detail. They explained all options clearly and ensured my assets would be protected according to my wishes.',
    created_at: '2024-12-06T11:00:00Z',
    is_verified: true
  },
  {
    id: 'review-013',
    case_id: 'case-007',
    reviewer_user_id: 'user-client-002',
    firm_id: 'firm-001',
    rating: 4.9,
    category_ratings: { communication: 5, timeliness: 5, expertise: 5, value: 4 },
    title: 'Unmatched legal expertise',
    body: 'Al Mansoori provided outstanding counsel during my criminal case. Their strategic approach and courtroom expertise resulted in a favorable outcome. Worth every dirham.',
    created_at: '2024-12-11T09:00:00Z',
    is_verified: true
  },
  {
    id: 'review-014',
    case_id: 'case-009',
    reviewer_user_id: 'user-client-004',
    firm_id: 'firm-014',
    rating: 4.5,
    category_ratings: { communication: 5, timeliness: 4, expertise: 5, value: 4 },
    title: 'Strong injury case representation',
    body: 'Marina Legal Solutions showed deep expertise in personal injury law. They fought hard for maximum compensation. The multilingual team was a huge advantage.',
    created_at: '2024-12-09T13:30:00Z',
    is_verified: true
  },
  {
    id: 'review-015',
    case_id: 'case-010',
    reviewer_user_id: 'user-client-005',
    firm_id: 'firm-010',
    rating: 4.7,
    category_ratings: { communication: 5, timeliness: 4, expertise: 5, value: 5 },
    title: 'Excellent banking dispute resolution',
    body: 'Skyline Legal Partners navigated the complex banking regulations expertly. They successfully resolved my frozen account issue and restored access quickly.',
    created_at: '2024-12-07T10:30:00Z',
    is_verified: true
  },
  {
    id: 'review-016',
    case_id: 'case-011',
    reviewer_user_id: 'user-client-001',
    firm_id: 'firm-004',
    rating: 4.8,
    category_ratings: { communication: 5, timeliness: 5, expertise: 5, value: 4 },
    title: 'Comprehensive shareholder agreement',
    body: 'Emirates Shield draft a thorough shareholder agreement that covered all scenarios. Their ADGM expertise was invaluable. Highly responsive throughout the process.',
    created_at: '2024-12-04T15:00:00Z',
    is_verified: true
  },
  {
    id: 'review-017',
    case_id: 'case-013',
    reviewer_user_id: 'user-client-002',
    firm_id: 'firm-007',
    rating: 4.6,
    category_ratings: { communication: 5, timeliness: 4, expertise: 5, value: 4 },
    title: 'Effective debt recovery service',
    body: 'Falcon Legal pursued the debt recovery case aggressively and professionally. They recovered most of the outstanding amount through skilled negotiation.',
    created_at: '2024-12-02T12:00:00Z',
    is_verified: true
  },
  {
    id: 'review-018',
    case_id: 'case-002',
    reviewer_user_id: 'user-client-002',
    firm_id: 'firm-020',
    rating: 4.8,
    category_ratings: { communication: 5, timeliness: 5, expertise: 5, value: 4 },
    title: 'Fast and professional DIFC setup',
    body: 'Sapphire Justice made the business setup process incredibly smooth. Their DIFC knowledge is top-notch. Quick responses and clear guidance at every step.',
    created_at: '2024-12-13T09:00:00Z',
    is_verified: true
  },
  {
    id: 'review-019',
    case_id: 'case-003',
    reviewer_user_id: 'user-client-003',
    firm_id: 'firm-006',
    rating: 4.0,
    category_ratings: { communication: 4, timeliness: 4, expertise: 4, value: 5 },
    title: 'Good value family law service',
    body: 'Desert Rose provided competent family law representation at a reasonable price. While not the fastest, the service was thorough and caring. Good option for budget-conscious clients.',
    created_at: '2024-11-25T14:30:00Z',
    is_verified: true
  },
  {
    id: 'review-020',
    case_id: 'case-004',
    reviewer_user_id: 'user-client-004',
    firm_id: 'firm-001',
    rating: 4.9,
    category_ratings: { communication: 5, timeliness: 5, expertise: 5, value: 4 },
    title: 'Premium employment law service',
    body: 'Al Mansoori handled my employment dispute with exceptional skill. They recovered all my benefits plus compensation. Their expertise in UAE labor law is unmatched.',
    created_at: '2024-11-22T11:00:00Z',
    is_verified: true
  },
  {
    id: 'review-021',
    case_id: 'case-005',
    reviewer_user_id: 'user-client-005',
    firm_id: 'firm-010',
    rating: 4.6,
    category_ratings: { communication: 5, timeliness: 4, expertise: 5, value: 4 },
    title: 'Strong IP portfolio protection',
    body: 'Skyline Legal provided comprehensive trademark registration across GCC. Their understanding of IP law and regional variations was impressive. Successful registrations.',
    created_at: '2024-12-14T10:00:00Z',
    is_verified: true
  },
  {
    id: 'review-022',
    case_id: 'case-008',
    reviewer_user_id: 'user-client-003',
    firm_id: 'firm-004',
    rating: 4.7,
    category_ratings: { communication: 5, timeliness: 4, expertise: 5, value: 4 },
    title: 'Thorough contract negotiation',
    body: 'Emirates Shield negotiated excellent terms on our commercial lease. They identified issues we would have missed and saved us significant money long-term.',
    created_at: '2024-11-18T13:00:00Z',
    is_verified: true
  },
  {
    id: 'review-023',
    case_id: 'case-010',
    reviewer_user_id: 'user-client-005',
    firm_id: 'firm-014',
    rating: 4.4,
    category_ratings: { communication: 4, timeliness: 4, expertise: 5, value: 4 },
    title: 'Competent banking law advice',
    body: 'Marina Legal Solutions provided sound advice on my banking dispute. The multilingual team was helpful for communication with various parties. Successful resolution.',
    created_at: '2024-12-15T11:30:00Z',
    is_verified: true
  },
  {
    id: 'review-024',
    case_id: 'case-012',
    reviewer_user_id: 'user-client-003',
    firm_id: 'firm-012',
    rating: 3.9,
    category_ratings: { communication: 4, timeliness: 4, expertise: 4, value: 4 },
    title: 'Adequate notary service',
    body: 'Palm Tree completed the notary service adequately. The process was straightforward but took longer than expected. Good communication throughout.',
    created_at: '2024-11-12T09:00:00Z',
    is_verified: true
  },
  {
    id: 'review-025',
    case_id: 'case-014',
    reviewer_user_id: 'user-client-004',
    firm_id: 'firm-011',
    rating: 4.3,
    category_ratings: { communication: 4, timeliness: 4, expertise: 5, value: 4 },
    title: 'Accurate legal translation',
    body: 'Al Shamsi provided accurate translation services. The certified translations were accepted without issues. Hindi language support was particularly valuable.',
    created_at: '2024-11-08T14:00:00Z',
    is_verified: true
  },
  {
    id: 'review-026',
    case_id: 'case-001',
    reviewer_user_id: 'user-client-001',
    firm_id: 'firm-008',
    rating: 4.2,
    category_ratings: { communication: 4, timeliness: 4, expertise: 4, value: 5 },
    title: 'Cost-effective property advice',
    body: 'Oasis Law Firm provided practical, affordable advice on property matters. While less prestigious than larger firms, they delivered good results at reasonable rates.',
    created_at: '2024-11-20T10:30:00Z',
    is_verified: true
  },
  {
    id: 'review-027',
    case_id: 'case-006',
    reviewer_user_id: 'user-client-001',
    firm_id: 'firm-010',
    rating: 4.7,
    category_ratings: { communication: 5, timeliness: 5, expertise: 5, value: 4 },
    title: 'Excellent will and estate planning',
    body: 'Skyline Legal crafted a comprehensive will that addressed all my complex asset situations. Their DIFC expertise ensured everything was properly structured. Very satisfied.',
    created_at: '2024-12-16T09:00:00Z',
    is_verified: true
  },
  {
    id: 'review-028',
    case_id: 'case-013',
    reviewer_user_id: 'user-client-002',
    firm_id: 'firm-001',
    rating: 4.9,
    category_ratings: { communication: 5, timeliness: 5, expertise: 5, value: 4 },
    title: 'Superior debt recovery service',
    body: 'Al Mansoori recovered the full amount owed plus interest. Their aggressive yet professional approach yielded excellent results. The best in the business.',
    created_at: '2024-12-17T11:00:00Z',
    is_verified: true
  },
  {
    id: 'review-029',
    case_id: 'case-015',
    reviewer_user_id: 'user-client-005',
    firm_id: 'firm-002',
    rating: 2.5,
    category_ratings: { communication: 3, timeliness: 2, expertise: 3, value: 2 },
    title: 'Disappointing insurance dispute service',
    body: 'Habtoor & Partners were slow to respond and did not achieve a favorable outcome in my insurance dispute. The case is still ongoing with limited progress. Expected better.',
    created_at: '2024-12-18T14:00:00Z',
    is_verified: true
  },
  {
    id: 'review-030',
    case_id: 'case-007',
    reviewer_user_id: 'user-client-002',
    firm_id: 'firm-020',
    rating: 4.8,
    category_ratings: { communication: 5, timeliness: 5, expertise: 5, value: 4 },
    title: 'Exceptional criminal defense',
    body: 'Sapphire Justice provided outstanding criminal defense. Their preparation was thorough and courtroom presence commanding. Charges were reduced significantly.',
    created_at: '2024-12-19T10:00:00Z',
    is_verified: true
  }
];
